export enum ENVKEY {
  EMAIL = "EMAIL",
  PASSWORD = "PASSWORD",
  USERNAME = "USER_NAME",
  WORKSPACE_HOST = "WORKSPACE_HOST",
  CI = "CI",
  DEFAULT_WORKSPACE_NAME = "DEFAULT_WORKSPACE_NAME",
  RUN_GLOBAL_SETUP = "RUN_GLOBAL_SETUP",
}
